version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "7777:7777"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "start"]
